version: '3.8'

services:

  frontend:
    container_name: ualspeed-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:3000"  
    networks:
      - ualspeed-net
    restart: unless-stopped
    
  results-service:
    container_name: results-service
    build: 
      context: ./results_service
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    depends_on:
      - postgres-results
    environment:
      - DB_NAME=${RESULTS_DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=postgres-results
      - DB_PORT=${DB_PORT}
      - RESULTS_SERVICE=${RESULTS_SERVICE}
      - DATA_SERVICE=${DATA_SERVICE}
    networks:
      - ualspeed-net

  postgres-results:
    image: postgres:15
    container_name: postgres-results
    volumes:
      - ./results_service/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - results_data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${RESULTS_POSTGRES_DB}
    ports:
      - "5433:5432"
    networks:
      - ualspeed-net

  data-service:
    container_name: data-service
    build:
      context: ./data_service
      dockerfile: Dockerfile
    ports:
      - "5003:5003"
    depends_on:
      - postgres-data
    environment:
      - DB_NAME=${DDB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=postgres-data
      - DB_PORT=${DB_PORT}
      - DATA_SERVICE=${DATA_SERVICE}
      - RESULTS_SERVICE=${RESULTS_SERVICE}
    networks:
      - ualspeed-net

  postgres-data:
    image: postgres:15
    container_name: postgres-data
    volumes:
      - ./data_service/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - data_data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DDB_POSTGRES_DB}
    ports:
      - "5434:5432"
    networks:
      - ualspeed-net

networks:
  ualspeed-net:
    driver: bridge

volumes:
  results_data:
  data_data: